import type { MetadataRoute } from 'next'
import { APP_URL } from '@/lib/seo'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/products',
          '/templates',
          '/apps',
          '/components',
          '/ai-projects',
          '/ecommerce',
          '/mobile-apps',
          '/browser-extensions',
          '/developer-tools',
          '/best-ai-coding-tools',
          '/product/',
          '/seller/',
          '/top-sellers',
          '/about',
          '/blog',
          '/blog/',
          '/support',
          '/contact',
          '/community',
          '/careers',
          '/press',
          '/partners',
          '/affiliates',
          '/enterprise',
          '/integrations',
          '/roadmap',
          '/changelog',
          '/trust',
          '/security',
          '/status',
          '/pricing',
          '/docs',
          '/api-docs',
          '/terms',
          '/privacy',
          '/cookies',
          '/refund',
          '/license',
          '/dmca',
          '/gdpr',
          '/accessibility',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/buyer/',
          '/panel/',
          '/auth/',
          '/checkout/',
          '/cart',
          '/style-guide',
        ],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
  }
}
